name: Cypress CI/CD

on: 
  push:
    branches: [Action]
  workflow_dispatch:   # <- bisa run manual kapan aja

jobs: 
    run-tests:
      runs-on: ubuntu-latest

      steps:
        #Checkout Repository
        - name: Checkout Repository
          uses: actions/checkout@v3
        
        #Setup Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with: 
            node-version: '18' #versi node.js bisa 16 atau 20 tergantung kebutuhan project
        
        #Instal dependencies
        - name: Install dependencies
          run: npm install

        #run cypress
        - name: Run Cypress tests
          run: npx cypress run


